# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        Anaxago\CoreBundle\Entity\User:
            algorithm: bcrypt

    providers:
        anaxago_provider:
            entity:
                class: AnaxagoCoreBundle:User
                property: username
        api_key_provider:
            id: Anaxago\CoreBundle\Security\ApiKeyUserProvider

    firewalls:
        api:
            pattern: ^/api
            stateless: true
            simple_preauth:
                authenticator: Anaxago\CoreBundle\Security\ApiKeyAuthenticator
            provider: api_key_provider
        main:
            provider: anaxago_provider
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/investir, roles: ROLE_USER }
        - { path: ^/api, roles: ROLE_USER }
