<?php

namespace Anaxago\CoreBundle\Repository;

use Anaxago\CoreBundle\Entity\Project;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Finds all projects (not archived).
     *
     * @return Project[].
     */
    public function findAll()
    {
        return $this->findBy([
            'archived' => false
        ]);
    }
}
