anaxago_core_admin_index:
    path: /
    defaults: { _controller: AnaxagoCoreBundle:Admin:index }

anaxago_core_admin_project_add:
    path: /projets/ajouter
    defaults: { _controller: AnaxagoCoreBundle:Project:create }

anaxago_core_admin_project_edit:
    path: /projets/{project}/modifier
    defaults: { _controller: AnaxagoCoreBundle:Project:edit }
    requirements: { project: \d+ }

anaxago_core_admin_project_destroy:
    path: /projets/{project}
    defaults: { _controller: AnaxagoCoreBundle:Project:destroy }
    requirements: { project: \d+ }
    methods: DELETE

anaxago_core_admin_project_investors:
    path: /projects/{project}/investisseurs
    defaults: { _controller: AnaxagoCoreBundle:Investors:index }
    requirements: { project: \d+ }