anaxago_core_admin_index:
    path: /
    defaults: { _controller: AnaxagoCoreBundle:Admin:index }

anaxago_core_admin_project_add:
    path: /projets/ajouter
    defaults: { _controller: AnaxagoCoreBundle:Project:create }