anaxago_core_api_projects:
    path: /projects
    defaults: { _controller: AnaxagoCoreBundle:Api\Project:index }

anaxago_core_api_invest:
    path: /invest
    defaults: { _controller: AnaxagoCoreBundle:Api\Invest:store }