anaxago_core_homepage:
    path:     /
    defaults: { _controller: AnaxagoCoreBundle:Default:index }

anaxago_core_admin:
    resource: "@AnaxagoCoreBundle/Resources/config/admin_routing.yml"
    prefix:   /admin

anaxago_core_invest:
    path: /investir
    defaults: { _controller: AnaxagoCoreBundle:Invest:store }
    methods: POST